services:
  - type: web
    name: django-loyiha
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn loyiha.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: loyiha.settings
          python manage.py migrate
startCommand: >
  python manage.py migrate &&
  gunicorn loyiha.wsgi:application
